import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "./components/Providers";
import { THEME_COLORS } from "./lib/themeColors";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// 在首次绘制前决定主题，写进 <html data-theme>。
// 为什么必须是阻塞式内联 script（而不是 useEffect）：
// 主题偏好存在 localStorage 里，服务端渲染时读不到。如果等 React 挂载后再设，
// 用户会先看到一帧错误主题再"闪"成正确的——这就是 FOUC
// (flash of unstyled content)。内联 script 在 <head> 里同步执行，
// 浏览器解析到它就停下来跑完，所以属性在任何像素画出来之前就已经写好了。
// 整段包在 try/catch 里：隐私模式下 localStorage 可能直接抛异常，
// 抛了就退回系统偏好，不能让主题脚本拖垮整个页面。
// 颜色从共享常量插值进来（构建期完成），保证脚本和 useTheme 用的是同一份值。
// 插的是我们自己代码里的字面量，不是任何用户输入，所以没有注入面。
const themeScript = `
(function () {
  var COLORS = { light: "${THEME_COLORS.light}", dark: "${THEME_COLORS.dark}" };
  function apply(t) {
    document.documentElement.setAttribute("data-theme", t);
    var m = document.querySelector('meta[name="theme-color"]');
    if (m) m.setAttribute("content", COLORS[t]);
  }
  try {
    var t = localStorage.getItem("theme");
    if (t !== "light" && t !== "dark") {
      t = window.matchMedia("(prefers-color-scheme: light)").matches
        ? "light"
        : "dark";
    }
    apply(t);
  } catch (e) {
    apply("dark");
  }
})();
`;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // suppressHydrationWarning：上面的 script 会在 React 接管前修改 <html> 的属性，
    // 服务端渲染出来的 HTML 里没有 data-theme，两边对不上会触发 hydration 警告。
    // 这个 prop 告诉 React「这一层的属性差异是预期的，别报错」——
    // 它只作用于这一个元素本身，不会向下影响子树。
    <html
      lang="en"
      suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <head>
        {/* meta 必须写在 script 之前——脚本要 querySelector 到它才能改 content。
            这里给的是深色默认值，与 tokens.css 的 :root 一致；
            脚本随后按真实主题覆盖。*/}
        <meta name="theme-color" content={THEME_COLORS.dark} />
        <script dangerouslySetInnerHTML={{ __html: themeScript }} />
      </head>
      <body className="min-h-full flex flex-col">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
